version: '3.8'

services:
  server:
    container_name: nestjs-ocr-server
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3000:3000
  db:
    container_name: nestjs-ocr-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db-data: