services:
  server:
    container_name: nestjs-ocr-server
    build:
      context: .
      target: dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/api/src
    depends_on:
      - db

  db:
    container_name: nestjs-ocr-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  db-data: